/* JS */ gapi.loaded_0(function(_){var window=this;
var ea,fa,ia,ja,sa,ma,wa,za,Ha;_.da=function(a){return function(){return _.ca[a].apply(this,arguments)}};_._DumpException=function(a){throw a;};_.ca=[];ea="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};fa="undefined"!=typeof window&&window===this?this:"undefined"!=typeof window.global&&null!=window.global?window.global:this;ia=function(){ia=function(){};fa.Symbol||(fa.Symbol=ja)};
ja=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();sa=function(){ia();var a=fa.Symbol.iterator;a||(a=fa.Symbol.iterator=fa.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&ea(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return ma(this)}});sa=function(){}};ma=function(a){var b=0;return wa(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})};wa=function(a){sa();a={next:a};a[fa.Symbol.iterator]=function(){return this};return a};
_.xa=function(a){sa();var b=a[window.Symbol.iterator];return b?b.call(a):ma(a)};_.ya="function"==typeof Object.create?Object.create:function(a){var b=function(){};b.prototype=a;return new b};if("function"==typeof Object.setPrototypeOf)za=Object.setPrototypeOf;else{var Ca;a:{var Da={a:!0},Ea={};try{Ea.__proto__=Da;Ca=Ea.a;break a}catch(a){}Ca=!1}za=Ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}_.Ga=za;
Ha=function(a,b){if(b){var c=fa;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ea(c,a,{configurable:!0,writable:!0,value:b})}};Ha("Array.prototype.find",function(a){return a?a:function(a,c){a:{var b=this;b instanceof String&&(b=String(b));for(var e=b.length,f=0;f<e;f++){var h=b[f];if(a.call(c,h,f,b)){a=h;break a}}a=void 0}return a}});var Ia=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
Ha("WeakMap",function(a){function b(a){Ia(a,d)||ea(a,d,{value:{}})}function c(a){var c=Object[a];c&&(Object[a]=function(a){b(a);return c(a)})}if(function(){if(!a||!Object.seal)return!1;try{var b=Object.seal({}),c=Object.seal({}),d=new a([[b,2],[c,3]]);if(2!=d.get(b)||3!=d.get(c))return!1;d["delete"](b);d.set(c,4);return!d.has(b)&&4==d.get(c)}catch(n){return!1}}())return a;var d="$jscomp_hidden_"+Math.random();c("freeze");c("preventExtensions");c("seal");var e=0,f=function(a){this.Aa=(e+=Math.random()+
1).toString();if(a){ia();sa();a=_.xa(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};f.prototype.set=function(a,c){b(a);if(!Ia(a,d))throw Error("a`"+a);a[d][this.Aa]=c;return this};f.prototype.get=function(a){return Ia(a,d)?a[d][this.Aa]:void 0};f.prototype.has=function(a){return Ia(a,d)&&Ia(a[d],this.Aa)};f.prototype["delete"]=function(a){return Ia(a,d)&&Ia(a[d],this.Aa)?delete a[d][this.Aa]:!1};return f});
Ha("Map",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),c=new a(_.xa([[b,"s"]]));if("s"!=c.get(b)||1!=c.size||c.get({x:4})||c.set({x:4},"t")!=c||2!=c.size)return!1;var d=c.entries(),e=d.next();if(e.done||e.value[0]!=b||"s"!=e.value[1])return!1;e=d.next();return e.done||4!=e.value[0].x||"t"!=e.value[1]||!d.next().done?!1:!0}catch(q){return!1}}())return a;ia();sa();var b=new window.WeakMap,c=function(a){this.nf=
{};this.Te=f();this.size=0;if(a){a=_.xa(a);for(var b;!(b=a.next()).done;)b=b.value,this.set(b[0],b[1])}};c.prototype.set=function(a,b){a=0===a?0:a;var c=d(this,a);c.list||(c.list=this.nf[c.id]=[]);c.le?c.le.value=b:(c.le={next:this.Te,Ni:this.Te.Ni,head:this.Te,key:a,value:b},c.list.push(c.le),this.Te.Ni.next=c.le,this.Te.Ni=c.le,this.size++);return this};c.prototype["delete"]=function(a){a=d(this,a);return a.le&&a.list?(a.list.splice(a.index,1),a.list.length||delete this.nf[a.id],a.le.Ni.next=a.le.next,
a.le.next.Ni=a.le.Ni,a.le.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.nf={};this.Te=this.Te.Ni=f();this.size=0};c.prototype.has=function(a){return!!d(this,a).le};c.prototype.get=function(a){return(a=d(this,a).le)&&a.value};c.prototype.entries=function(){return e(this,function(a){return[a.key,a.value]})};c.prototype.keys=function(){return e(this,function(a){return a.key})};c.prototype.values=function(){return e(this,function(a){return a.value})};c.prototype.forEach=function(a,b){for(var c=
this.entries(),d;!(d=c.next()).done;)d=d.value,a.call(b,d[1],d[0],this)};c.prototype[window.Symbol.iterator]=c.prototype.entries;var d=function(a,c){var d=c&&typeof c;"object"==d||"function"==d?b.has(c)?d=b.get(c):(d=""+ ++h,b.set(c,d)):d="p_"+c;var e=a.nf[d];if(e&&Ia(a.nf,d))for(a=0;a<e.length;a++){var f=e[a];if(c!==c&&f.key!==f.key||c===f.key)return{id:d,list:e,index:a,le:f}}return{id:d,list:e,index:-1,le:void 0}},e=function(a,b){var c=a.Te;return wa(function(){if(c){for(;c.head!=a.Te;)c=c.Ni;for(;c.next!=
c.head;)return c=c.next,{done:!1,value:b(c)};c=null}return{done:!0,value:void 0}})},f=function(){var a={};return a.Ni=a.next=a.head=a},h=0;return c});
Ha("Set",function(a){if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var b=Object.seal({x:4}),d=new a(_.xa([b]));if(!d.has(b)||1!=d.size||d.add(b)!=d||1!=d.size||d.add({x:4})!=d||2!=d.size)return!1;var e=d.entries(),f=e.next();if(f.done||f.value[0]!=b||f.value[1]!=b)return!1;f=e.next();return f.done||f.value[0]==b||4!=f.value[0].x||f.value[1]!=f.value[0]?!1:e.next().done}catch(h){return!1}}())return a;ia();sa();var b=function(a){this.U=
new window.Map;if(a){a=_.xa(a);for(var b;!(b=a.next()).done;)this.add(b.value)}this.size=this.U.size};b.prototype.add=function(a){a=0===a?0:a;this.U.set(a,a);this.size=this.U.size;return this};b.prototype["delete"]=function(a){a=this.U["delete"](a);this.size=this.U.size;return a};b.prototype.clear=function(){this.U.clear();this.size=0};b.prototype.has=function(a){return this.U.has(a)};b.prototype.entries=function(){return this.U.entries()};b.prototype.values=function(){return this.U.values()};b.prototype.keys=
b.prototype.values;b.prototype[window.Symbol.iterator]=b.prototype.values;b.prototype.forEach=function(a,b){var c=this;this.U.forEach(function(d){return a.call(b,d,d,c)})};return b});Ha("Number.isFinite",function(a){return a?a:function(a){return"number"!==typeof a?!1:!(0,window.isNaN)(a)&&window.Infinity!==a&&-window.Infinity!==a}});Ha("Object.is",function(a){return a?a:function(a,c){return a===c?0!==a||1/a===1/c:a!==a&&c!==c}});_.Ja=_.Ja||{};_.m=this;_.r=function(a){return void 0!==a};
_.v=function(a){return"string"==typeof a};
_.La=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};_.Ma=function(a){return"array"==_.La(a)};_.Na="closure_uid_"+(1E9*Math.random()>>>0);_.Oa=Date.now||function(){return+new Date};_.w=function(a,b){a=a.split(".");var c=_.m;a[0]in c||"undefined"==typeof c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&_.r(b)?c[d]=b:c=c[d]&&c[d]!==Object.prototype[d]?c[d]:c[d]={}};
_.B=function(a,b){function c(){}c.prototype=b.prototype;a.H=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.gp=function(a,c,f){for(var d=Array(arguments.length-2),e=2;e<arguments.length;e++)d[e-2]=arguments[e];return b.prototype[c].apply(a,d)}};
_.Ra=window.osapi=window.osapi||{};
window.___jsl=window.___jsl||{};
(window.___jsl.cd=window.___jsl.cd||[]).push({gwidget:{parsetags:"explicit"},appsapi:{plus_one_service:"/plus/v1"},csi:{rate:.01},poshare:{hangoutContactPickerServer:"https://plus.google.com"},gappsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},appsutil:{required_scopes:["https://www.googleapis.com/auth/plus.me","https://www.googleapis.com/auth/plus.people.recommended"],display_on_page_ready:!1},
"oauth-flow":{authUrl:"https://accounts.google.com/o/oauth2/auth",proxyUrl:"https://accounts.google.com/o/oauth2/postmessageRelay",redirectUri:"postmessage"},iframes:{sharebox:{params:{json:"&"},url:":socialhost:/:session_prefix:_/sharebox/dialog"},plus:{url:":socialhost:/:session_prefix:_/widget/render/badge?usegapi=1"},":socialhost:":"https://apis.google.com",":im_socialhost:":"https://plus.googleapis.com",domains_suggest:{url:"https://domains.google.com/suggest/flow"},card:{params:{s:"#",userid:"&"},
url:":socialhost:/:session_prefix:_/hovercard/internalcard"},":signuphost:":"https://plus.google.com",":gplus_url:":"https://plus.google.com",plusone:{url:":socialhost:/:session_prefix:_/+1/fastbutton?usegapi=1"},plus_share:{url:":socialhost:/:session_prefix:_/+1/sharebutton?plusShare=true&usegapi=1"},plus_circle:{url:":socialhost:/:session_prefix:_/widget/plus/circle?usegapi=1"},plus_followers:{url:":socialhost:/_/im/_/widget/render/plus/followers?usegapi=1"},configurator:{url:":socialhost:/:session_prefix:_/plusbuttonconfigurator?usegapi=1"},
appcirclepicker:{url:":socialhost:/:session_prefix:_/widget/render/appcirclepicker"},page:{url:":socialhost:/:session_prefix:_/widget/render/page?usegapi=1"},person:{url:":socialhost:/:session_prefix:_/widget/render/person?usegapi=1"},community:{url:":ctx_socialhost:/:session_prefix::im_prefix:_/widget/render/community?usegapi=1"},follow:{url:":socialhost:/:session_prefix:_/widget/render/follow?usegapi=1"},commentcount:{url:":socialhost:/:session_prefix:_/widget/render/commentcount?usegapi=1"},comments:{url:":socialhost:/:session_prefix:_/widget/render/comments?usegapi=1"},
youtube:{url:":socialhost:/:session_prefix:_/widget/render/youtube?usegapi=1"},reportabuse:{url:":socialhost:/:session_prefix:_/widget/render/reportabuse?usegapi=1"},additnow:{url:":socialhost:/additnow/additnow.html"},udc_webconsentflow:{url:"https://myaccount.google.com/webconsent?usegapi=1"},appfinder:{url:"https://gsuite.google.com/:session_prefix:marketplace/appfinder?usegapi=1"},":source:":"1p"},poclient:{update_session:"google.updateSessionCallback"},"googleapis.config":{methods:{"pos.plusones.list":!0,
"pos.plusones.get":!0,"pos.plusones.insert":!0,"pos.plusones.delete":!0,"pos.plusones.getSignupState":!0},versions:{pos:"v1"},rpc:"/rpc",root:"https://content.googleapis.com","root-1p":"https://clients6.google.com",useGapiForXd3:!0,xd3:"/static/proxy.html",developerKey:"AIzaSyCKSbrvQasunBoV16zDH9R33D88CeLr9gQ",auth:{useInterimAuth:!1}},report:{apis:["iframes\\..*","gadgets\\..*","gapi\\.appcirclepicker\\..*","gapi\\.client\\..*"],rate:1E-4},client:{perApiBatch:!0}});

var Xa,db,eb;_.Sa=function(a){return"number"==typeof a};_.Ta=function(){};_.Ua=function(a){var b=_.La(a);return"array"==b||"object"==b&&"number"==typeof a.length};_.Va=function(a){return"function"==_.La(a)};_.Wa=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};Xa=0;_.$a=function(a){return a[_.Na]||(a[_.Na]=++Xa)};db=function(a,b,c){return a.call.apply(a.bind,arguments)};
eb=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};_.C=function(a,b,c){_.C=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?db:eb;return _.C.apply(null,arguments)};
_.fb=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(_.v(a))return _.v(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1};_.hb=Array.prototype.lastIndexOf?function(a,b){return Array.prototype.lastIndexOf.call(a,b,a.length-1)}:function(a,b){var c=a.length-1;0>c&&(c=Math.max(0,a.length+c));if(_.v(a))return _.v(b)&&1==b.length?a.lastIndexOf(b,c):-1;for(;0<=c;c--)if(c in a&&a[c]===b)return c;return-1};
_.jb=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.v(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)};_.lb=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=[],e=0,f=_.v(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};
_.mb=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=_.v(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};_.nb=Array.prototype.some?function(a,b,c){return Array.prototype.some.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.v(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&b.call(c,e[f],f,a))return!0;return!1}; _.ob=Array.prototype.every?function(a,b,c){return Array.prototype.every.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=_.v(a)?a.split(""):a,f=0;f<d;f++)if(f in e&&!b.call(c,e[f],f,a))return!1;return!0};_.qb=function(a,b){return 0<=(0,_.fb)(a,b)};
var tb;_.rb=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};_.sb=String.prototype.repeat?function(a,b){return a.repeat(b)}:function(a,b){return Array(b+1).join(a)};
_.ub=function(a,b){var c=0;a=(0,_.rb)(String(a)).split(".");b=(0,_.rb)(String(b)).split(".");for(var d=Math.max(a.length,b.length),e=0;0==c&&e<d;e++){var f=a[e]||"",h=b[e]||"";do{f=/(\d*)(\D*)(.*)/.exec(f)||["","","",""];h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];if(0==f[0].length&&0==h[0].length)break;c=tb(0==f[1].length?0:(0,window.parseInt)(f[1],10),0==h[1].length?0:(0,window.parseInt)(h[1],10))||tb(0==f[2].length,0==h[2].length)||tb(f[2],h[2]);f=f[3];h=h[3]}while(0==c)}return c}; tb=function(a,b){return a<b?-1:a>b?1:0};_.xb=2147483648*Math.random()|0;
a:{var Bb=_.m.navigator;if(Bb){var Cb=Bb.userAgent;if(Cb){_.yb=Cb;break a}}_.yb=""}_.Db=function(a){return-1!=_.yb.indexOf(a)};var Fb;_.Eb=function(a,b,c){for(var d in a)b.call(c,a[d],d,a)};Fb="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");_.Gb=function(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Fb.length;f++)c=Fb[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};
_.Hb=function(){return _.Db("Opera")};_.Ib=function(){return _.Db("Trident")||_.Db("MSIE")};_.Jb=function(){return _.Db("iPhone")&&!_.Db("iPod")&&!_.Db("iPad")};_.Kb=function(){return _.Jb()||_.Db("iPad")||_.Db("iPod")};var Lb=function(a){Lb[" "](a);return a},Pb;Lb[" "]=_.Ta;_.Mb=function(a,b){try{return Lb(a[b]),!0}catch(c){}return!1};Pb=function(a,b){var c=Ob;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var fc,gc,Ob,oc;_.Qb=_.Hb();_.D=_.Ib();_.Tb=_.Db("Edge");_.Ub=_.Tb||_.D;_.Vb=_.Db("Gecko")&&!(-1!=_.yb.toLowerCase().indexOf("webkit")&&!_.Db("Edge"))&&!(_.Db("Trident")||_.Db("MSIE"))&&!_.Db("Edge");_.Wb=-1!=_.yb.toLowerCase().indexOf("webkit")&&!_.Db("Edge");_.Xb=_.Wb&&_.Db("Mobile");_.Yb=_.Db("Macintosh");_.Zb=_.Db("Windows");_.$b=_.Db("Linux")||_.Db("CrOS");_.ac=_.Db("Android");_.bc=_.Jb();_.cc=_.Db("iPad");_.dc=_.Db("iPod");_.ec=_.Kb();
fc=function(){var a=_.m.document;return a?a.documentMode:void 0};a:{var hc="",ic=function(){var a=_.yb;if(_.Vb)return/rv:([^\);]+)(\)|;)/.exec(a);if(_.Tb)return/Edge\/([\d\.]+)/.exec(a);if(_.D)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(_.Wb)return/WebKit\/(\S+)/.exec(a);if(_.Qb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ic&&(hc=ic?ic[1]:"");if(_.D){var jc=fc();if(null!=jc&&jc>(0,window.parseFloat)(hc)){gc=String(jc);break a}}gc=hc}_.kc=gc;Ob={}; _.lc=function(a){return Pb(a,function(){return 0<=_.ub(_.kc,a)})};_.nc=function(a){return Number(_.mc)>=a};var pc=_.m.document;oc=pc&&_.D?fc()||("CSS1Compat"==pc.compatMode?(0,window.parseInt)(_.kc,10):5):void 0;_.mc=oc;

var rc,vc,wc,xc,yc,zc,Ac,Bc;_.qc=function(a,b){return _.ca[a]=b};_.sc=function(a){return Array.prototype.concat.apply([],arguments)};_.tc=function(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};_.uc=function(a,b){return 0==a.lastIndexOf(b,0)};vc=/&/g;wc=/</g;xc=/>/g;yc=/"/g;zc=/'/g;Ac=/\x00/g;Bc=/[\x00&<>"']/;
_.Cc=function(a){if(!Bc.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(vc,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(wc,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(xc,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(yc,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(zc,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ac,"&#0;"));return a};_.Dc=function(a){return String(a).replace(/\-([a-z])/g,function(a,c){return c.toUpperCase()})};_.Ec=function(a,b){for(var c in a)if(a[c]==b)return!0;return!1};
var Fc,Hc;Fc=!_.D||_.nc(9);Hc=!_.Vb&&!_.D||_.D&&_.nc(9)||_.Vb&&_.lc("1.9.1");_.Ic=_.D&&!_.lc("9");_.Jc=_.D||_.Qb||_.Wb;_.Kc=_.D&&!_.nc(9);var Lc;_.Mc=function(){this.Dw="";this.LP=Lc};_.Mc.prototype.Bh=!0;_.Mc.prototype.$f=function(){return this.Dw};_.Mc.prototype.toString=function(){return"Const{"+this.Dw+"}"};_.Nc=function(a){return a instanceof _.Mc&&a.constructor===_.Mc&&a.LP===Lc?a.Dw:"type_error:Const"};Lc={};_.Oc=function(a){var b=new _.Mc;b.Dw=a;return b};_.Oc("");
var Pc;_.Qc=function(){this.dC="";this.VP=Pc};_.Qc.prototype.Bh=!0;_.Qc.prototype.$f=function(){return this.dC};_.Qc.prototype.KA=!0;_.Qc.prototype.ql=function(){return 1};_.Rc=function(a){if(a instanceof _.Qc&&a.constructor===_.Qc&&a.VP===Pc)return a.dC;_.La(a);return"type_error:TrustedResourceUrl"};_.Tc=function(a){return _.Sc(_.Nc(a))};Pc={};_.Sc=function(a){var b=new _.Qc;b.dC=a;return b};
var Xc,Uc,Yc;_.Vc=function(){this.$l="";this.vP=Uc};_.Vc.prototype.Bh=!0;_.Vc.prototype.$f=function(){return this.$l};_.Vc.prototype.KA=!0;_.Vc.prototype.ql=function(){return 1};_.Wc=function(a){if(a instanceof _.Vc&&a.constructor===_.Vc&&a.vP===Uc)return a.$l;_.La(a);return"type_error:SafeUrl"};Xc=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;_.$c=function(a){if(a instanceof _.Vc)return a;a=a.Bh?a.$f():String(a);Xc.test(a)||(a="about:invalid#zClosurez");return Yc(a)}; _.ad=function(a){if(a instanceof _.Vc)return a;a=a.Bh?a.$f():String(a);Xc.test(a)||(a="about:invalid#zClosurez");return Yc(a)};Uc={};Yc=function(a){var b=new _.Vc;b.$l=a;return b};Yc("about:blank");
_.cd=function(){this.cC="";this.uP=_.bd};_.cd.prototype.Bh=!0;_.bd={};_.cd.prototype.$f=function(){return this.cC};_.cd.prototype.Ci=function(a){this.cC=a;return this};_.dd=(new _.cd).Ci("");_.fd=function(){this.bC="";this.tP=_.ed};_.fd.prototype.Bh=!0;_.ed={};_.hd=function(a){a=_.Nc(a);return 0===a.length?gd:(new _.fd).Ci(a)};_.fd.prototype.$f=function(){return this.bC};_.fd.prototype.Ci=function(a){this.bC=a;return this};var gd=(new _.fd).Ci("");
var jd;_.kd=function(){this.$l="";this.sP=jd;this.LG=null};_.kd.prototype.KA=!0;_.kd.prototype.ql=function(){return this.LG};_.kd.prototype.Bh=!0;_.kd.prototype.$f=function(){return this.$l};_.ld=function(a){if(a instanceof _.kd&&a.constructor===_.kd&&a.sP===jd)return a.$l;_.La(a);return"type_error:SafeHtml"};jd={};_.md=function(a,b){return(new _.kd).Ci(a,b)};_.kd.prototype.Ci=function(a,b){this.$l=a;this.LG=b;return this};_.md("<!DOCTYPE html>",0);_.nd=_.md("",0);_.od=_.md("<br>",0);
_.pd=function(a,b){b=b instanceof _.Vc?b:_.ad(b);a.href=_.Wc(b)};var vd,yd,Ad;_.sd=function(a){return a?new _.qd(_.rd(a)):rc||(rc=new _.qd)};_.td=function(a,b){return _.v(b)?a.getElementById(b):b};
_.ud=function(a,b,c,d){a=d||a;b=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(b||c))return a.querySelectorAll(b+(c?"."+c:""));if(c&&a.getElementsByClassName){a=a.getElementsByClassName(c);if(b){d={};for(var e=0,f=0,h;h=a[f];f++)b==h.nodeName&&(d[e++]=h);d.length=e;return d}return a}a=a.getElementsByTagName(b||"*");if(c){d={};for(f=e=0;h=a[f];f++)b=h.className,"function"==typeof b.split&&_.qb(b.split(/\s+/),c)&&(d[e++]=h);d.length=e;return d}return a};
_.wd=function(a,b){_.Eb(b,function(b,d){b&&b.Bh&&(b=b.$f());"style"==d?a.style.cssText=b:"class"==d?a.className=b:"for"==d?a.htmlFor=b:vd.hasOwnProperty(d)?a.setAttribute(vd[d],b):_.uc(d,"aria-")||_.uc(d,"data-")?a.setAttribute(d,b):a[d]=b})};vd={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};
_.xd=function(a){return a?a.parentWindow||a.defaultView:window};_.zd=function(a,b){var c=String(b[0]),d=b[1];if(!Fc&&d&&(d.name||d.type)){c=["<",c];d.name&&c.push(' name="',_.Cc(d.name),'"');if(d.type){c.push(' type="',_.Cc(d.type),'"');var e={};_.Gb(e,d);delete e.type;d=e}c.push(">");c=c.join("")}c=a.createElement(c);d&&(_.v(d)?c.className=d:_.Ma(d)?c.className=d.join(" "):_.wd(c,d));2<b.length&&yd(a,c,b,2);return c};
yd=function(a,b,c,d){function e(c){c&&b.appendChild(_.v(c)?a.createTextNode(c):c)}for(;d<c.length;d++){var f=c[d];!_.Ua(f)||_.Wa(f)&&0<f.nodeType?e(f):(0,_.jb)(Ad(f)?_.tc(f):f,e)}};_.Cd=function(a){return window.document.createElement(String(a))};_.Dd=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
_.Ed=function(a,b){yd(_.rd(a),a,arguments,1)};_.Fd=function(a){for(var b;b=a.firstChild;)a.removeChild(b)};_.Gd=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};_.Hd=function(a){return a&&a.parentNode?a.parentNode.removeChild(a):null};_.Id=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return _.Hd(a)}};
_.Jd=function(a){return Hc&&void 0!=a.children?a.children:(0,_.lb)(a.childNodes,function(a){return 1==a.nodeType})};_.Kd=function(a){return _.Wa(a)&&1==a.nodeType};_.Ld=function(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a};_.rd=function(a){return 9==a.nodeType?a:a.ownerDocument||a.document};
_.Md=function(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else _.Fd(a),a.appendChild(_.rd(a).createTextNode(String(b)))};Ad=function(a){if(a&&"number"==typeof a.length){if(_.Wa(a))return"function"==typeof a.item||"string"==typeof a.item;if(_.Va(a))return"function"==typeof a.item}return!1};
_.qd=function(a){this.Va=a||_.m.document||window.document};_.g=_.qd.prototype;_.g.Ea=_.sd;_.g.XC=_.da(0);_.g.mb=function(){return this.Va};_.g.S=function(a){return _.td(this.Va,a)};_.g.getElementsByTagName=function(a,b){return(b||this.Va).getElementsByTagName(String(a))};_.g.ma=function(a,b,c){return _.zd(this.Va,arguments)};_.g.createElement=function(a){return this.Va.createElement(String(a))};_.g.createTextNode=function(a){return this.Va.createTextNode(String(a))};
_.g.ub=function(){var a=this.Va;return a.parentWindow||a.defaultView};_.g.appendChild=function(a,b){a.appendChild(b)};_.g.append=_.Ed;_.g.canHaveChildren=_.Dd;_.g.ze=_.Fd;_.g.aJ=_.Gd;_.g.removeNode=_.Hd;_.g.dS=_.Id;_.g.Az=_.Jd;_.g.isElement=_.Kd;_.g.contains=_.Ld;_.g.Eh=_.da(1);
/*
 gapi.loader.OBJECT_CREATE_TEST_OVERRIDE &&*/
_.Nd=window;_.Od=window.document;_.Rd=_.Nd.location;_.Sd=/\[native code\]/;_.Td=function(a,b,c){return a[b]=a[b]||c};_.G=function(){var a;if((a=Object.create)&&_.Sd.test(a))a=a(null);else{a={};for(var b in a)a[b]=void 0}return a};_.Ud=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};_.Vd=function(a,b){a=a||{};for(var c in a)_.Ud(a,c)&&(b[c]=a[c])};_.Wd=_.Td(_.Nd,"gapi",{});
_.Xd=function(a,b,c){var d=new RegExp("([#].*&|[#])"+b+"=([^&#]*)","g");b=new RegExp("([?#].*&|[?#])"+b+"=([^&#]*)","g");if(a=a&&(d.exec(a)||b.exec(a)))try{c=(0,window.decodeURIComponent)(a[2])}catch(e){}return c};_.Yd=new RegExp(/^/.source+/([a-zA-Z][-+.a-zA-Z0-9]*:)?/.source+/(\/\/[^\/?#]*)?/.source+/([^?#]*)?/.source+/(\?([^#]*))?/.source+/(#((#|[^#])*))?/.source+/$/.source);
_.Zd=new RegExp(/(%([^0-9a-fA-F%]|[0-9a-fA-F]([^0-9a-fA-F%])?)?)*/.source+/%($|[^0-9a-fA-F]|[0-9a-fA-F]($|[^0-9a-fA-F]))/.source,"g");_.$d=new RegExp(/\/?\??#?/.source+"("+/[\/?#]/i.source+"|"+/[\uD800-\uDBFF]/i.source+"|"+/%[c-f][0-9a-f](%[89ab][0-9a-f]){0,2}(%[89ab]?)?/i.source+"|"+/%[0-9a-f]?/i.source+")$","i");
_.ce=function(a,b,c){_.be(a,b,c,"add","at")};_.be=function(a,b,c,d,e){if(a[d+"EventListener"])a[d+"EventListener"](b,c,!1);else if(a[e+"tachEvent"])a[e+"tachEvent"]("on"+b,c)};_.de=_.Td(_.Nd,"___jsl",_.G());_.Td(_.de,"I",0);_.Td(_.de,"hel",10);var ee,fe,ge,he,ie,je,ke;ee=function(a){var b=window.___jsl=window.___jsl||{};b[a]=b[a]||[];return b[a]};fe=function(a){var b=window.___jsl=window.___jsl||{};b.cfg=!a&&b.cfg||{};return b.cfg};ge=function(a){return"object"===typeof a&&/\[native code\]/.test(a.push)};
he=function(a,b,c){if(b&&"object"===typeof b)for(var d in b)!Object.prototype.hasOwnProperty.call(b,d)||c&&"___goc"===d&&"undefined"===typeof b[d]||(a[d]&&b[d]&&"object"===typeof a[d]&&"object"===typeof b[d]&&!ge(a[d])&&!ge(b[d])?he(a[d],b[d]):b[d]&&"object"===typeof b[d]?(a[d]=ge(b[d])?[]:{},he(a[d],b[d])):a[d]=b[d])};
ie=function(a){if(a&&!/^\s+$/.test(a)){for(;0==a.charCodeAt(a.length-1);)a=a.substring(0,a.length-1);try{var b=window.JSON.parse(a)}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ("+a+"\n)"))()}catch(c){}if("object"===typeof b)return b;try{b=(new Function("return ({"+a+"\n})"))()}catch(c){}return"object"===typeof b?b:{}}};
je=function(a,b){var c={___goc:void 0};a.length&&a[a.length-1]&&Object.hasOwnProperty.call(a[a.length-1],"___goc")&&"undefined"===typeof a[a.length-1].___goc&&(c=a.pop());he(c,b);a.push(c)};
ke=function(a){fe(!0);var b=window.___gcfg,c=ee("cu"),d=window.___gu;b&&b!==d&&(je(c,b),window.___gu=b);b=ee("cu");var e=window.document.scripts||window.document.getElementsByTagName("script")||[];d=[];var f=[];f.push.apply(f,ee("us"));for(var h=0;h<e.length;++h)for(var k=e[h],l=0;l<f.length;++l)k.src&&0==k.src.indexOf(f[l])&&d.push(k);0==d.length&&0<e.length&&e[e.length-1].src&&d.push(e[e.length-1]);for(e=0;e<d.length;++e)d[e].getAttribute("gapi_processed")||(d[e].setAttribute("gapi_processed",!0),
(f=d[e])?(h=f.nodeType,f=3==h||4==h?f.nodeValue:f.textContent||f.innerText||f.innerHTML||""):f=void 0,(f=ie(f))&&b.push(f));a&&je(c,a);d=ee("cd");a=0;for(b=d.length;a<b;++a)he(fe(),d[a],!0);d=ee("ci");a=0;for(b=d.length;a<b;++a)he(fe(),d[a],!0);a=0;for(b=c.length;a<b;++a)he(fe(),c[a],!0)};_.H=function(a,b){var c=fe();if(!a)return c;a=a.split("/");for(var d=0,e=a.length;c&&"object"===typeof c&&d<e;++d)c=c[a[d]];return d===a.length&&void 0!==c?c:b}; _.le=function(a,b){var c;if("string"===typeof a){var d=c={};a=a.split("/");for(var e=0,f=a.length;e<f-1;++e){var h={};d=d[a[e]]=h}d[a[e]]=b}else c=a;ke(c)};
var me=function(){var a=window.__GOOGLEAPIS;a&&(a.googleapis&&!a["googleapis.config"]&&(a["googleapis.config"]=a.googleapis),_.Td(_.de,"ci",[]).push(a),window.__GOOGLEAPIS=void 0)};me&&me();ke();_.w("gapi.config.get",_.H);_.w("gapi.config.update",_.le);
_.ne=function(a,b){for(var c=1;c<arguments.length;c++){var d=arguments[c];if(_.Ua(d)){var e=a.length||0,f=d.length||0;a.length=e+f;for(var h=0;h<f;h++)a[e+h]=d[h]}else a.push(d)}};_.oe=function(a){return/^[\s\xa0]*$/.test(a)};_.se=function(a,b){var c=b||window.document;if(c.getElementsByClassName)a=c.getElementsByClassName(a)[0];else{c=window.document;var d=b||c;a=d.querySelectorAll&&d.querySelector&&a?d.querySelector(a?"."+a:""):_.ud(c,"*",a,b)[0]||null}return a||null};

var ze,Ae,Be,Ce,De,Ee,Fe,Ge,He,Ie,Je,Ke,Le,Me,Ne,Oe,Pe,Qe,Re,Se,Te,Ue,We,Xe,Ye,Ze,$e,af,bf,cf,df,gf,hf;Be=void 0;Ce=function(a){try{return _.m.JSON.parse.call(_.m.JSON,a)}catch(b){return!1}};De=function(a){return Object.prototype.toString.call(a)};Ee=De(0);Fe=De(new Date(0));Ge=De(!0);He=De("");Ie=De({});Je=De([]);
Ke=function(a,b){if(b)for(var c=0,d=b.length;c<d;++c)if(a===b[c])throw new TypeError("Converting circular structure to JSON");d=typeof a;if("undefined"!==d){c=Array.prototype.slice.call(b||[],0);c[c.length]=a;b=[];var e=De(a);if(null!=a&&"function"===typeof a.toJSON&&(Object.prototype.hasOwnProperty.call(a,"toJSON")||(e!==Je||a.constructor!==Array&&a.constructor!==Object)&&(e!==Ie||a.constructor!==Array&&a.constructor!==Object)&&e!==He&&e!==Ee&&e!==Ge&&e!==Fe))return Ke(a.toJSON.call(a),c);if(null==
a)b[b.length]="null";else if(e===Ee)a=Number(a),(0,window.isNaN)(a)||(0,window.isNaN)(a-a)?a="null":-0===a&&0>1/a&&(a="-0"),b[b.length]=String(a);else if(e===Ge)b[b.length]=String(!!Number(a));else{if(e===Fe)return Ke(a.toISOString.call(a),c);if(e===Je&&De(a.length)===Ee){b[b.length]="[";var f=0;for(d=Number(a.length)>>0;f<d;++f)f&&(b[b.length]=","),b[b.length]=Ke(a[f],c)||"null";b[b.length]="]"}else if(e==He&&De(a.length)===Ee){b[b.length]='"';f=0;for(c=Number(a.length)>>0;f<c;++f)d=String.prototype.charAt.call(a,
f),e=String.prototype.charCodeAt.call(a,f),b[b.length]="\b"===d?"\\b":"\f"===d?"\\f":"\n"===d?"\\n":"\r"===d?"\\r":"\t"===d?"\\t":"\\"===d||'"'===d?"\\"+d:31>=e?"\\u"+(e+65536).toString(16).substr(1):32<=e&&65535>=e?d:"\ufffd";b[b.length]='"'}else if("object"===d){b[b.length]="{";d=0;for(f in a)Object.prototype.hasOwnProperty.call(a,f)&&(e=Ke(a[f],c),void 0!==e&&(d++&&(b[b.length]=","),b[b.length]=Ke(f),b[b.length]=":",b[b.length]=e));b[b.length]="}"}else return}return b.join("")}};Le=/[\0-\x07\x0b\x0e-\x1f]/;
Me=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*[\0-\x1f]/;Ne=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\[^\\\/"bfnrtu]/;Oe=/^([^"]*"([^\\"]|\\.)*")*[^"]*"([^"\\]|\\.)*\\u([0-9a-fA-F]{0,3}[^0-9a-fA-F])/;Pe=/"([^\0-\x1f\\"]|\\[\\\/"bfnrt]|\\u[0-9a-fA-F]{4})*"/g;Qe=/-?(0|[1-9][0-9]*)(\.[0-9]+)?([eE][-+]?[0-9]+)?/g;Re=/[ \t\n\r]+/g;Se=/[^"]:/;Te=/""/g;Ue=/true|false|null/g;We=/00/;Xe=/[\{]([^0\}]|0[^:])/;Ye=/(^|\[)[,:]|[,:](\]|\}|[,:]|$)/;Ze=/[^\[,:][\[\{]/;$e=/^(\{|\}|\[|\]|,|:|0)+/;af=/\u2028/g;
bf=/\u2029/g;
cf=function(a){a=String(a);if(Le.test(a)||Me.test(a)||Ne.test(a)||Oe.test(a))return!1;var b=a.replace(Pe,'""');b=b.replace(Qe,"0");b=b.replace(Re,"");if(Se.test(b))return!1;b=b.replace(Te,"0");b=b.replace(Ue,"0");if(We.test(b)||Xe.test(b)||Ye.test(b)||Ze.test(b)||!b||(b=b.replace($e,"")))return!1;a=a.replace(af,"\\u2028").replace(bf,"\\u2029");b=void 0;try{b=Be?[Ce(a)]:eval("(function (var_args) {\n  return Array.prototype.slice.call(arguments, 0);\n})(\n"+a+"\n)")}catch(c){return!1}return b&&1===
b.length?b[0]:!1};df=function(){var a=((_.m.document||{}).scripts||[]).length;if((void 0===ze||void 0===Be||Ae!==a)&&-1!==Ae){ze=Be=!1;Ae=-1;try{try{Be=!!_.m.JSON&&'{"a":[3,true,"1970-01-01T00:00:00.000Z"]}'===_.m.JSON.stringify.call(_.m.JSON,{a:[3,!0,new Date(0)],c:function(){}})&&!0===Ce("true")&&3===Ce('[{"a":3}]')[0].a}catch(b){}ze=Be&&!Ce("[00]")&&!Ce('"\u0007"')&&!Ce('"\\0"')&&!Ce('"\\v"')}finally{Ae=a}}};_.ef=function(a){if(-1===Ae)return!1;df();return(ze?Ce:cf)(a)};
_.ff=function(a){if(-1!==Ae)return df(),Be?_.m.JSON.stringify.call(_.m.JSON,a):Ke(a)};gf=!Date.prototype.toISOString||"function"!==typeof Date.prototype.toISOString||"1970-01-01T00:00:00.000Z"!==(new Date(0)).toISOString();
hf=function(){var a=Date.prototype.getUTCFullYear.call(this);return[0>a?"-"+String(1E6-a).substr(1):9999>=a?String(1E4+a).substr(1):"+"+String(1E6+a).substr(1),"-",String(101+Date.prototype.getUTCMonth.call(this)).substr(1),"-",String(100+Date.prototype.getUTCDate.call(this)).substr(1),"T",String(100+Date.prototype.getUTCHours.call(this)).substr(1),":",String(100+Date.prototype.getUTCMinutes.call(this)).substr(1),":",String(100+Date.prototype.getUTCSeconds.call(this)).substr(1),".",String(1E3+Date.prototype.getUTCMilliseconds.call(this)).substr(1), "Z"].join("")};Date.prototype.toISOString=gf?hf:Date.prototype.toISOString;

var eh;eh=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?#]*)?\/u\/(\d)\//;
_.fh=function(a){var b=_.H("googleapis.config/sessionIndex");"string"===typeof b&&254<b.length&&(b=null);null==b&&(b=window.__X_GOOG_AUTHUSER);"string"===typeof b&&254<b.length&&(b=null);if(null==b){var c=window.google;c&&(b=c.authuser)}"string"===typeof b&&254<b.length&&(b=null);null==b&&(a=a||window.location.href,b=_.Xd(a,"authuser")||null,null==b&&(b=(b=a.match(eh))?b[1]:null));if(null==b)return null;b=String(b);254<b.length&&(b=null);return b};

var ih=function(){this.tj=-1};_.jh=function(){this.tj=64;this.Fc=[];this.Xx=[];this.bQ=[];this.Jv=[];this.Jv[0]=128;for(var a=1;a<this.tj;++a)this.Jv[a]=0;this.Jw=this.An=0;this.reset()};_.B(_.jh,ih);_.jh.prototype.reset=function(){this.Fc[0]=1732584193;this.Fc[1]=4023233417;this.Fc[2]=2562383102;this.Fc[3]=271733878;this.Fc[4]=3285377520;this.Jw=this.An=0};
var kh=function(a,b,c){c||(c=0);var d=a.bQ;if(_.v(b))for(var e=0;16>e;e++)d[e]=b.charCodeAt(c)<<24|b.charCodeAt(c+1)<<16|b.charCodeAt(c+2)<<8|b.charCodeAt(c+3),c+=4;else for(e=0;16>e;e++)d[e]=b[c]<<24|b[c+1]<<16|b[c+2]<<8|b[c+3],c+=4;for(e=16;80>e;e++){var f=d[e-3]^d[e-8]^d[e-14]^d[e-16];d[e]=(f<<1|f>>>31)&4294967295}b=a.Fc[0];c=a.Fc[1];var h=a.Fc[2],k=a.Fc[3],l=a.Fc[4];for(e=0;80>e;e++){if(40>e)if(20>e){f=k^c&(h^k);var n=1518500249}else f=c^h^k,n=1859775393;else 60>e?(f=c&h|k&(c|h),n=2400959708):
(f=c^h^k,n=3395469782);f=(b<<5|b>>>27)+f+l+n+d[e]&4294967295;l=k;k=h;h=(c<<30|c>>>2)&4294967295;c=b;b=f}a.Fc[0]=a.Fc[0]+b&4294967295;a.Fc[1]=a.Fc[1]+c&4294967295;a.Fc[2]=a.Fc[2]+h&4294967295;a.Fc[3]=a.Fc[3]+k&4294967295;a.Fc[4]=a.Fc[4]+l&4294967295};
_.jh.prototype.update=function(a,b){if(null!=a){_.r(b)||(b=a.length);for(var c=b-this.tj,d=0,e=this.Xx,f=this.An;d<b;){if(0==f)for(;d<=c;)kh(this,a,d),d+=this.tj;if(_.v(a))for(;d<b;){if(e[f]=a.charCodeAt(d),++f,++d,f==this.tj){kh(this,e);f=0;break}}else for(;d<b;)if(e[f]=a[d],++f,++d,f==this.tj){kh(this,e);f=0;break}}this.An=f;this.Jw+=b}};
_.jh.prototype.digest=function(){var a=[],b=8*this.Jw;56>this.An?this.update(this.Jv,56-this.An):this.update(this.Jv,this.tj-(this.An-56));for(var c=this.tj-1;56<=c;c--)this.Xx[c]=b&255,b/=256;kh(this,this.Xx);for(c=b=0;5>c;c++)for(var d=24;0<=d;d-=8)a[b]=this.Fc[c]>>d&255,++b;return a};

_.lh=function(){this.rD=new _.jh};_.g=_.lh.prototype;_.g.reset=function(){this.rD.reset()};_.g.NM=function(a){this.rD.update(a)};_.g.KG=function(){return this.rD.digest()};_.g.SD=function(a){a=(0,window.unescape)((0,window.encodeURIComponent)(a));for(var b=[],c=0,d=a.length;c<d;++c)b.push(a.charCodeAt(c));this.NM(b)};_.g.Jg=function(){for(var a=this.KG(),b="",c=0;c<a.length;c++)b+="0123456789ABCDEF".charAt(Math.floor(a[c]/16))+"0123456789ABCDEF".charAt(a[c]%16);return b};

var Ij,Hj,Oj,Pj,Jj,Mj,Kj,Qj,Lj;_.Nj=function(){if(Hj){var a=new _.Nd.Uint32Array(1);Ij.getRandomValues(a);a=Number("0."+a[0])}else a=Jj,a+=(0,window.parseInt)(Kj.substr(0,20),16),Kj=Lj(Kj),a/=Mj+Math.pow(16,20);return a};Ij=_.Nd.crypto;Hj=!1;Oj=0;Pj=0;Jj=1;Mj=0;Kj="";Qj=function(a){a=a||_.Nd.event;var b=a.screenX+a.clientX<<16;b+=a.screenY+a.clientY;b*=(new Date).getTime()%1E6;Jj=Jj*b%Mj;0<Oj&&++Pj==Oj&&_.be(_.Nd,"mousemove",Qj,"remove","de")};Lj=function(a){var b=new _.lh;b.SD(a);return b.Jg()};
Hj=!!Ij&&"function"==typeof Ij.getRandomValues;Hj||(Mj=1E6*(window.screen.width*window.screen.width+window.screen.height),Kj=Lj(_.Od.cookie+"|"+_.Od.location+"|"+(new Date).getTime()+"|"+Math.random()),Oj=_.H("random/maxObserveMousemove")||0,0!=Oj&&_.ce(_.Nd,"mousemove",Qj));

var Sj,Wj,Xj,Yj,Zj,ak,bk,ck,dk,ek,fk,gk,hk,lk,nk,ok,pk,qk,rk,sk;_.Rj=function(a,b){b=b instanceof _.Vc?b:_.ad(b);a.href=_.Wc(b)};_.Tj=function(a){return!!a&&"object"===typeof a&&_.Sd.test(a.push)};_.Uj=function(a){for(var b=0;b<this.length;b++)if(this[b]===a)return b;return-1};_.Vj=function(a,b){if(!a)throw Error(b||"");};Wj=/&/g;Xj=/</g;Yj=/>/g;Zj=/"/g;ak=/'/g;bk=function(a){return String(a).replace(Wj,"&amp;").replace(Xj,"&lt;").replace(Yj,"&gt;").replace(Zj,"&quot;").replace(ak,"&#39;")};ck=/[\ud800-\udbff][\udc00-\udfff]|[^!-~]/g;
dk=/%([a-f]|[0-9a-fA-F][a-f])/g;ek=/^(https?|ftp|file|chrome-extension):$/i;
fk=function(a){a=String(a);a=a.replace(ck,function(a){try{return(0,window.encodeURIComponent)(a)}catch(f){return(0,window.encodeURIComponent)(a.replace(/^[^%]+$/g,"\ufffd"))}}).replace(_.Zd,function(a){return a.replace(/%/g,"%25")}).replace(dk,function(a){return a.toUpperCase()});a=a.match(_.Yd)||[];var b=_.G(),c=function(a){return a.replace(/\\/g,"%5C").replace(/\^/g,"%5E").replace(/`/g,"%60").replace(/\{/g,"%7B").replace(/\|/g,"%7C").replace(/\}/g,"%7D")},d=!!(a[1]||"").match(ek);b.gp=c((a[1]||
"")+(a[2]||"")+(a[3]||(a[2]&&d?"/":"")));d=function(a){return c(a.replace(/\?/g,"%3F").replace(/#/g,"%23"))};b.query=a[5]?[d(a[5])]:[];b.nh=a[7]?[d(a[7])]:[];return b};gk=function(a){return a.gp+(0<a.query.length?"?"+a.query.join("&"):"")+(0<a.nh.length?"#"+a.nh.join("&"):"")};hk=function(a,b){var c=[];if(a)for(var d in a)if(_.Ud(a,d)&&null!=a[d]){var e=b?b(a[d]):a[d];c.push((0,window.encodeURIComponent)(d)+"="+(0,window.encodeURIComponent)(e))}return c};
_.ik=function(a,b,c,d){a=fk(a);a.query.push.apply(a.query,hk(b,d));a.nh.push.apply(a.nh,hk(c,d));return gk(a)};
_.jk=function(a,b){var c=fk(b);b=c.gp;c.query.length&&(b+="?"+c.query.join(""));c.nh.length&&(b+="#"+c.nh.join(""));var d="";2E3<b.length&&(c=b,b=b.substr(0,2E3),b=b.replace(_.$d,""),d=c.substr(b.length));var e=a.createElement("div");a=a.createElement("a");c=fk(b);b=c.gp;c.query.length&&(b+="?"+c.query.join(""));c.nh.length&&(b+="#"+c.nh.join(""));a.href=b;e.appendChild(a);e.innerHTML=e.innerHTML;b=String(e.firstChild.href);e.parentNode&&e.parentNode.removeChild(e);c=fk(b+d);b=c.gp;c.query.length&&
(b+="?"+c.query.join(""));c.nh.length&&(b+="#"+c.nh.join(""));return b};_.kk=/^https?:\/\/[^\/%\\?#\s]+\/[^\s]*$/i;lk=function(a){for(;a.firstChild;)a.removeChild(a.firstChild)};_.mk=function(a,b){var c=_.Td(_.de,"watt",_.G());_.Td(c,a,b)};nk=/^https?:\/\/(?:\w|[\-\.])+\.google\.(?:\w|[\-:\.])+(?:\/[^\?#]*)?\/b\/(\d{10,21})\//;
ok=function(a){var b=_.H("googleapis.config/sessionDelegate");"string"===typeof b&&21<b.length&&(b=null);null==b&&(b=(a=(a||window.location.href).match(nk))?a[1]:null);if(null==b)return null;b=String(b);21<b.length&&(b=null);return b};pk=function(){var a=_.de.onl;if(!a){a=_.G();_.de.onl=a;var b=_.G();a.e=function(a){var c=b[a];c&&(delete b[a],c())};a.a=function(a,d){b[a]=d};a.r=function(a){delete b[a]}}return a};qk=function(a,b){b=b.onload;return"function"===typeof b?(pk().a(a,b),b):null}; rk=function(a){_.Vj(/^\w+$/.test(a),"Unsupported id - "+a);pk();return'onload="window.___jsl.onl.e(&#34;'+a+'&#34;)"'};sk=function(a){pk().r(a)};
var uk,vk,zk;_.tk={allowtransparency:"true",frameborder:"0",hspace:"0",marginheight:"0",marginwidth:"0",scrolling:"no",style:"",tabindex:"0",vspace:"0",width:"100%"};uk={allowtransparency:!0,onload:!0};vk=0;_.wk=function(a,b){var c=0;do var d=b.id||["I",vk++,"_",(new Date).getTime()].join("");while(a.getElementById(d)&&5>++c);_.Vj(5>c,"Error creating iframe id");return d};_.xk=function(a,b){return a?b+"/"+a:""};
_.yk=function(a,b,c,d){var e={},f={};a.documentMode&&9>a.documentMode&&(e.hostiemode=a.documentMode);_.Vd(d.queryParams||{},e);_.Vd(d.fragmentParams||{},f);var h=d.pfname;var k=_.G();_.H("iframes/dropLegacyIdParam")||(k.id=c);k._gfid=c;k.parent=a.location.protocol+"//"+a.location.host;c=_.Xd(a.location.href,"parent");h=h||"";!h&&c&&(h=_.Xd(a.location.href,"_gfid","")||_.Xd(a.location.href,"id",""),h=_.xk(h,_.Xd(a.location.href,"pfname","")));h||(c=_.ef(_.Xd(a.location.href,"jcp","")))&&"object"==
typeof c&&(h=_.xk(c.id,c.pfname));k.pfname=h;d.connectWithJsonParam&&(h={},h.jcp=_.ff(k),k=h);h=_.Xd(b,"rpctoken")||e.rpctoken||f.rpctoken;h||(h=d.rpctoken||String(Math.round(1E8*_.Nj())),k.rpctoken=h);d.rpctoken=h;_.Vd(k,d.connectWithQueryParams?e:f);k=a.location.href;a=_.G();(h=_.Xd(k,"_bsh",_.de.bsh))&&(a._bsh=h);(k=_.de.dpo?_.de.h:_.Xd(k,"jsh",_.de.h))&&(a.jsh=k);d.hintInFragment?_.Vd(a,f):_.Vd(a,e);return _.ik(b,e,f,d.paramsSerializer)};
zk=function(a){_.Vj(!a||_.kk.test(a),"Illegal url for new iframe - "+a)};
_.Ak=function(a,b,c,d,e){zk(c.src);var f,h=qk(d,c),k=h?rk(d):"";try{window.document.all&&(f=a.createElement('<iframe frameborder="'+bk(String(c.frameborder))+'" scrolling="'+bk(String(c.scrolling))+'" '+k+' name="'+bk(String(c.name))+'"/>'))}catch(n){}finally{f||(f=a.createElement("iframe"),h&&(f.onload=function(){f.onload=null;h.call(this)},sk(d)))}f.setAttribute("ng-non-bindable","");for(var l in c)a=c[l],"style"===l&&"object"===typeof a?_.Vd(a,f.style):uk[l]||f.setAttribute(l,String(a));(l=e&& e.beforeNode||null)||e&&e.dontclear||lk(b);b.insertBefore(f,l);f=l?l.previousSibling:b.lastChild;c.allowtransparency&&(f.allowTransparency=!0);return f};
var Bk,Ek;Bk=/^:[\w]+$/;_.Ck=/:([a-zA-Z_]+):/g;_.Dk=function(){var a=_.fh()||"0",b=ok();var c=_.fh(void 0)||a;var d=ok(void 0),e="";c&&(e+="u/"+(0,window.encodeURIComponent)(String(c))+"/");d&&(e+="b/"+(0,window.encodeURIComponent)(String(d))+"/");c=e||null;(e=(d=!1===_.H("isLoggedIn"))?"_/im/":"")&&(c="");var f=_.H("iframes/:socialhost:"),h=_.H("iframes/:im_socialhost:");return Sj={socialhost:f,ctx_socialhost:d?h:f,session_index:a,session_delegate:b,session_prefix:c,im_prefix:e}};
Ek=function(a,b){return _.Dk()[b]||""};_.Fk=function(a){return _.jk(_.Od,a.replace(_.Ck,Ek))};_.Gk=function(a){var b=a;Bk.test(a)&&(b=_.H("iframes/"+b.substring(1)+"/url"),_.Vj(!!b,"Unknown iframe url config for - "+a));return _.Fk(b)};
_.Hk=function(a,b,c){var d=c||{};c=d.attributes||{};_.Vj(!(d.allowPost||d.forcePost)||!c.onload,"onload is not supported by post iframe (allowPost or forcePost)");a=_.Gk(a);c=b.ownerDocument||_.Od;var e=_.wk(c,d);a=_.yk(c,a,e,d);var f=_.G();_.Vd(_.tk,f);_.Vd(d.attributes,f);f.name=f.id=e;f.src=a;d.eurl=a;var h=d||{},k=!!h.allowPost;if(h.forcePost||k&&2E3<a.length){h=fk(a);f.src="";d.dropDataPostorigin||(f["data-postorigin"]=a);a=_.Ak(c,b,f,e);if(-1!=window.navigator.userAgent.indexOf("WebKit")){var l=
a.contentWindow.document;l.open();f=l.createElement("div");k={};var n=e+"_inner";k.name=n;k.src="";k.style="display:none";_.Ak(c,f,k,n,d)}f=(d=h.query[0])?d.split("&"):[];d=[];for(k=0;k<f.length;k++)n=f[k].split("=",2),d.push([(0,window.decodeURIComponent)(n[0]),(0,window.decodeURIComponent)(n[1])]);h.query=[];f=gk(h);_.Vj(_.kk.test(f),"Invalid URL: "+f);h=c.createElement("form");h.action=f;h.method="POST";h.target=e;h.style.display="none";for(e=0;e<d.length;e++)f=c.createElement("input"),f.type= "hidden",f.name=d[e][0],f.value=d[e][1],h.appendChild(f);b.appendChild(h);h.submit();h.parentNode.removeChild(h);l&&l.close();b=a}else b=_.Ak(c,b,f,e,d);return b};

_.w("gapi.iframes.create",_.Hk);
_.w("gadgets.json.stringify",_.ff);_.w("gadgets.json.parse",_.ef);
_.Rf=window.gapi&&window.gapi.util||{};
_.Tf=function(a){if(!a)return"";a=a.split("#")[0].split("?")[0];a=a.toLowerCase();0==a.indexOf("//")&&(a=window.location.protocol+a);/^[\w\-]*:\/\//.test(a)||(a=window.location.href);var b=a.substring(a.indexOf("://")+3),c=b.indexOf("/");-1!=c&&(b=b.substring(0,c));a=a.substring(0,a.indexOf("://"));if("http"!==a&&"https"!==a&&"chrome-extension"!==a&&"file"!==a&&"android-app"!==a&&"chrome-search"!==a&&"app"!==a)throw Error("w`"+a);c="";var d=b.indexOf(":");if(-1!=d){var e=b.substring(d+1);b=b.substring(0, d);if("http"===a&&"80"!==e||"https"===a&&"443"!==e)c=":"+e}return a+"://"+b+c};

_.Rf.Qa=function(a){return _.Tf(a)};
var ue;ue=window.console;_.ve=function(a){ue&&ue.log&&ue.log(a)};_.we=function(a){ue&&(ue.error?ue.error(a):ue.log&&ue.log(a))};_.xe=function(){};
_.K=_.K||{};
_.K=_.K||{};
(function(){var a=null;_.K.Hc=function(b){var c="undefined"===typeof b;if(null!==a&&c)return a;var d={};b=b||window.location.href;var e=b.indexOf("?"),f=b.indexOf("#");b=(-1===f?b.substr(e+1):[b.substr(e+1,f-e-1),"&",b.substr(f+1)].join("")).split("&");e=window.decodeURIComponent?window.decodeURIComponent:window.unescape;f=0;for(var h=b.length;f<h;++f){var k=b[f].indexOf("=");if(-1!==k){var l=b[f].substring(0,k);k=b[f].substring(k+1);k=k.replace(/\+/g," ");try{d[l]=e(k)}catch(n){}}}c&&(a=d);return d}; _.K.Hc()})();
_.w("gadgets.util.getUrlParameters",_.K.Hc);
_.Xd(_.Nd.location.href,"rpctoken")&&_.ce(_.Od,"unload",function(){});
var ai=function(){this.rs={PK:Uh?"../"+Uh:null,zR:Vh,aI:Wh,Zba:Xh,ru:Yh,Hca:Zh};this.Ge=_.Nd;this.BK=this.vR;this.gS=/MSIE\s*[0-8](\D|$)/.test(window.navigator.userAgent);if(this.rs.PK){this.Ge=this.rs.aI(this.Ge,this.rs.PK);var a=this.Ge.document,b=a.createElement("script");b.setAttribute("type","text/javascript");b.text="window.doPostMsg=function(w,s,o) {window.setTimeout(function(){w.postMessage(s,o);},0);};";a.body.appendChild(b);this.BK=this.Ge.doPostMsg}this.sD={};this.QD={};a=(0,_.C)(this.lA,
this);_.ce(this.Ge,"message",a);_.Td(_.de,"RPMQ",[]).push(a);this.Ge!=this.Ge.parent&&$h(this,this.Ge.parent,'{"h":"'+(0,window.escape)(this.Ge.name)+'"}',"*")},bi=function(a){var b=null;0===a.indexOf('{"h":"')&&a.indexOf('"}')===a.length-2&&(b=(0,window.unescape)(a.substring(6,a.length-2)));return b},ci=function(a){if(!/^\s*{/.test(a))return!1;a=_.ef(a);return null!==a&&"object"===typeof a&&!!a.g};
ai.prototype.lA=function(a){var b=String(a.data);(0,_.xe)("gapi.rpc.receive("+Xh+"): "+(!b||512>=b.length?b:b.substr(0,512)+"... ("+b.length+" bytes)"));var c=0!==b.indexOf("!_");c||(b=b.substring(2));var d=ci(b);if(!c&&!d){if(!d&&(c=bi(b))){if(this.sD[c])this.sD[c]();else this.QD[c]=1;return}var e=a.origin,f=this.rs.zR;this.gS?_.Nd.setTimeout(function(){f(b,e)},0):f(b,e)}};ai.prototype.Ec=function(a,b){".."===a||this.QD[a]?(b(),delete this.QD[a]):this.sD[a]=b};
var $h=function(a,b,c,d){var e=ci(c)?"":"!_";(0,_.xe)("gapi.rpc.send("+Xh+"): "+(!c||512>=c.length?c:c.substr(0,512)+"... ("+c.length+" bytes)"));a.BK(b,e+c,d)};ai.prototype.vR=function(a,b,c){a.postMessage(b,c)};ai.prototype.send=function(a,b,c){(a=this.rs.aI(this.Ge,a))&&!a.closed&&$h(this,a,b,c)};
var di,ei,fi,gi,hi,ii,ji,ki,Uh,Xh,li,mi,ni,oi,Wh,Yh,qi,ri,wi,xi,zi,Zh,Bi,Ai,si,ti,Ci,Vh,Di,Ei;di=0;ei=[];fi={};gi={};hi=_.K.Hc;ii=hi();ji=ii.rpctoken;ki=ii.parent||_.Od.referrer;Uh=ii.rly;Xh=Uh||(_.Nd!==_.Nd.top||_.Nd.opener)&&_.Nd.name||"..";li=null;mi={};ni=function(){};oi={send:ni,Ec:ni};
Wh=function(a,b){"/"==b.charAt(0)&&(b=b.substring(1),a=_.Nd.top);for(b=b.split("/");b.length;){var c=b.shift();"{"==c.charAt(0)&&"}"==c.charAt(c.length-1)&&(c=c.substring(1,c.length-1));if(".."===c)a=a==a.parent?a.opener:a.parent;else if(".."!==c&&a.frames[c]){if(a=a.frames[c],!("postMessage"in a))throw"Not a window";}else return null}return a};Yh=function(a){return(a=fi[a])&&a.Ek};
qi=function(a){if(a.f in{})return!1;var b=a.t,c=fi[a.r];a=a.origin;return c&&(c.Ek===b||!c.Ek&&!b)&&(a===c.origin||"*"===c.origin)};ri=function(a){var b=a.id.split("/"),c=b[b.length-1],d=a.origin;return function(a){var b=a.origin;return a.f==c&&(d==b||"*"==d)}};_.ui=function(a,b,c){a=si(a);gi[a.name]={Mg:b,Sq:a.Sq,Ao:c||qi};ti()};_.vi=function(a){delete gi[si(a).name]};wi={};xi=function(a,b){(a=wi["_"+a])&&a[1](this)&&a[0].call(this,b)};
zi=function(a){var b=a.c;if(!b)return ni;var c=a.r,d=a.g?"legacy__":"";return function(){var a=[].slice.call(arguments,0);a.unshift(c,d+"__cb",null,b);_.yi.apply(null,a)}};Zh=function(a){li=a};Bi=function(a){mi[a]||(mi[a]=_.Nd.setTimeout(function(){mi[a]=!1;Ai(a)},0))};Ai=function(a){var b=fi[a];if(b&&b.ready){var c=b.fC;for(b.fC=[];c.length;)oi.send(a,_.ff(c.shift()),b.origin)}};si=function(a){return 0===a.indexOf("legacy__")?{name:a.substring(8),Sq:!0}:{name:a,Sq:!1}};
ti=function(){for(var a=_.H("rpc/residenceSec")||60,b=(new Date).getTime()/1E3,c=0,d;d=ei[c];++c){var e=d.im;if(!e||0<a&&b-d.timestamp>a)ei.splice(c,1),--c;else{var f=e.s,h=gi[f]||gi["*"];if(h)if(ei.splice(c,1),--c,e.origin=d.origin,d=zi(e),e.callback=d,h.Ao(e)){if("__cb"!==f&&!!h.Sq!=!!e.g)break;e=h.Mg.apply(e,e.a);void 0!==e&&d(e)}else(0,_.xe)("gapi.rpc.rejected("+Xh+"): "+f)}}};Ci=function(a,b,c){ei.push({im:a,origin:b,timestamp:(new Date).getTime()/1E3});c||ti()};
Vh=function(a,b){a=_.ef(a);Ci(a,b,!1)};Di=function(a){for(;a.length;)Ci(a.shift(),this.origin,!0);ti()};Ei=function(a){var b=!1;a=a.split("|");var c=a[0];0<=c.indexOf("/")&&(b=!0);return{id:c,origin:a[1]||"*",UA:b}};
_.Fi=function(a,b,c,d){var e=Ei(a);d&&(_.Nd.frames[e.id]=_.Nd.frames[e.id]||d);a=e.id;if(!fi.hasOwnProperty(a)){c=c||null;d=e.origin;if(".."===a)d=_.Rf.Qa(ki),c=c||ji;else if(!e.UA){var f=_.Od.getElementById(a);f&&(f=f.src,d=_.Rf.Qa(f),c=c||hi(f).rpctoken)}"*"===e.origin&&d||(d=e.origin);fi[a]={Ek:c,fC:[],origin:d,bZ:b,HK:function(){var b=a;fi[b].ready=1;Ai(b)}};oi.Ec(a,fi[a].HK)}return fi[a].HK};
_.yi=function(a,b,c,d){a=a||"..";_.Fi(a);a=a.split("|",1)[0];var e=b,f=[].slice.call(arguments,3),h=c,k=Xh,l=ji,n=fi[a],p=k,q=Ei(a);if(n&&".."!==a){if(q.UA){if(!(l=fi[a].bZ)){l=li?li.substring(1).split("/"):[Xh];p=l.length-1;for(var t=_.Nd.parent;t!==_.Nd.top;){var y=t.parent;if(!p--){for(var u=null,x=y.frames.length,F=0;F<x;++F)y.frames[F]==t&&(u=F);l.unshift("{"+u+"}")}t=y}l="/"+l.join("/")}p=l}else p=k="..";l=n.Ek}h&&q?(n=qi,q.UA&&(n=ri(q)),wi["_"+ ++di]=[h,n],h=di):h=null;f={s:e,f:k,r:p,t:l,c:h, a:f};e=si(e);f.s=e.name;f.g=e.Sq;fi[a].fC.push(f);Bi(a)};if("function"===typeof _.Nd.postMessage||"object"===typeof _.Nd.postMessage)oi=new ai,_.ui("__cb",xi,function(){return!0}),_.ui("_processBatch",Di,function(){return!0}),_.Fi("..");

_.Gi=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};_.Hi=function(a,b){a:{for(var c=a.length,d=_.v(a)?a.split(""):a,e=0;e<c;e++)if(e in d&&b.call(void 0,d[e],e,a)){b=e;break a}b=-1}return 0>b?null:_.v(a)?a.charAt(b):a[b]};_.Ii=[];_.Ji=[];_.Ki=!1;_.Li=function(a){_.Ii[_.Ii.length]=a;if(_.Ki)for(var b=0;b<_.Ji.length;b++)a((0,_.C)(_.Ji[b].wrap,_.Ji[b]))};

_.Mi=function(a){return function(){return a}}(!0);
var Ni,Oi,Ui;Ni=null;Oi=/^[\w+/_-]+[=]{0,2}$/;_.Pi=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,_.Pi);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))};_.B(_.Pi,Error);_.Pi.prototype.name="CustomError";_.Qi=function(a,b){for(var c in a)if(!(c in b)||a[c]!==b[c])return!1;for(c in b)if(!(c in a))return!1;return!0};_.Ri=function(a){var b={},c;for(c in a)b[c]=a[c];return b};
_.Si=function(a,b){a.src=_.Rc(b);if(null===Ni){a:{if((b=_.m.document.querySelector("script[nonce]"))&&(b=b.nonce||b.getAttribute("nonce"))&&Oi.test(b))break a;b=null}Ni=b||""}(b=Ni)&&a.setAttribute("nonce",b)};_.Ti=function(a){return a};Ui=function(a,b){this.rR=a;this.QY=b;this.wv=0;this.Te=null};Ui.prototype.get=function(){if(0<this.wv){this.wv--;var a=this.Te;this.Te=a.next;a.next=null}else a=this.rR();return a}; Ui.prototype.put=function(a){this.QY(a);100>this.wv&&(this.wv++,a.next=this.Te,this.Te=a)};
var Vi,Xi,Yi,Wi;Vi=function(a){_.m.setTimeout(function(){throw a;},0)};_.Zi=function(a){a=Wi(a);!_.Va(_.m.setImmediate)||_.m.Window&&_.m.Window.prototype&&!_.Db("Edge")&&_.m.Window.prototype.setImmediate==_.m.setImmediate?(Xi||(Xi=Yi()),Xi(a)):_.m.setImmediate(a)};
Yi=function(){var a=_.m.MessageChannel;"undefined"===typeof a&&"undefined"!==typeof window&&window.postMessage&&window.addEventListener&&!_.Db("Presto")&&(a=function(){var a=window.document.createElement("IFRAME");a.style.display="none";a.src="";window.document.documentElement.appendChild(a);var b=a.contentWindow;a=b.document;a.open();a.write("");a.close();var c="callImmediate"+Math.random(),d="file:"==b.location.protocol?"*":b.location.protocol+"//"+b.location.host;a=(0,_.C)(function(a){if(("*"==
d||a.origin==d)&&a.data==c)this.port1.onmessage()},this);b.addEventListener("message",a,!1);this.port1={};this.port2={postMessage:function(){b.postMessage(c,d)}}});if("undefined"!==typeof a&&!_.Ib()){var b=new a,c={},d=c;b.port1.onmessage=function(){if(_.r(c.next)){c=c.next;var a=c.cb;c.cb=null;a()}};return function(a){d.next={cb:a};d=d.next;b.port2.postMessage(0)}}return"undefined"!==typeof window.document&&"onreadystatechange"in window.document.createElement("SCRIPT")?function(a){var b=window.document.createElement("SCRIPT"); b.onreadystatechange=function(){b.onreadystatechange=null;b.parentNode.removeChild(b);b=null;a();a=null};window.document.documentElement.appendChild(b)}:function(a){_.m.setTimeout(a,0)}};Wi=_.Ti;_.Li(function(a){Wi=a});
var $i=function(){this.Uw=this.Do=null},bj=new Ui(function(){return new aj},function(a){a.reset()});$i.prototype.add=function(a,b){var c=bj.get();c.set(a,b);this.Uw?this.Uw.next=c:this.Do=c;this.Uw=c};$i.prototype.remove=function(){var a=null;this.Do&&(a=this.Do,this.Do=this.Do.next,this.Do||(this.Uw=null),a.next=null);return a};var aj=function(){this.next=this.scope=this.Mg=null};aj.prototype.set=function(a,b){this.Mg=a;this.scope=b;this.next=null}; aj.prototype.reset=function(){this.next=this.scope=this.Mg=null};
var cj,dj,ej,fj,hj;_.gj=function(a,b){cj||dj();ej||(cj(),ej=!0);fj.add(a,b)};dj=function(){if(_.m.Promise&&_.m.Promise.resolve){var a=_.m.Promise.resolve(void 0);cj=function(){a.then(hj)}}else cj=function(){_.Zi(hj)}};ej=!1;fj=new $i;hj=function(){for(var a;a=fj.remove();){try{a.Mg.call(a.scope)}catch(b){Vi(b)}bj.put(a)}ej=!1};
_.ij=function(a){a.prototype.then=a.prototype.then;a.prototype.$goog_Thenable=!0};_.jj=function(a){if(!a)return!1;try{return!!a.$goog_Thenable}catch(b){return!1}};var lj,mj,wj,uj;_.kj=function(a,b){this.Da=0;this.Pi=void 0;this.Tm=this.vj=this.hb=null;this.uu=this.fz=!1;if(a!=_.Ta)try{var c=this;a.call(b,function(a){c.Wg(2,a)},function(a){c.Wg(3,a)})}catch(d){this.Wg(3,d)}};lj=function(){this.next=this.context=this.On=this.gr=this.Uk=null;this.Yo=!1};lj.prototype.reset=function(){this.context=this.On=this.gr=this.Uk=null;this.Yo=!1};mj=new Ui(function(){return new lj},function(a){a.reset()});_.nj=function(a,b,c){var d=mj.get();d.gr=a;d.On=b;d.context=c;return d};
_.oj=function(a){if(a instanceof _.kj)return a;var b=new _.kj(_.Ta);b.Wg(2,a);return b};_.pj=function(a){return new _.kj(function(b,c){c(a)})};_.rj=function(a,b,c){qj(a,b,c,null)||_.gj(_.Gi(b,a))};_.tj=function(){var a,b,c=new _.kj(function(c,e){a=c;b=e});return new sj(c,a,b)};_.kj.prototype.then=function(a,b,c){return uj(this,_.Va(a)?a:null,_.Va(b)?b:null,c)};_.ij(_.kj);_.kj.prototype.JD=function(a,b){return uj(this,null,a,b)};
_.kj.prototype.cancel=function(a){0==this.Da&&_.gj(function(){var b=new vj(a);wj(this,b)},this)};wj=function(a,b){if(0==a.Da)if(a.hb){var c=a.hb;if(c.vj){for(var d=0,e=null,f=null,h=c.vj;h&&(h.Yo||(d++,h.Uk==a&&(e=h),!(e&&1<d)));h=h.next)e||(f=h);e&&(0==c.Da&&1==d?wj(c,b):(f?(d=f,d.next==c.Tm&&(c.Tm=d),d.next=d.next.next):xj(c),yj(c,e,3,b)))}a.hb=null}else a.Wg(3,b)};_.Aj=function(a,b){a.vj||2!=a.Da&&3!=a.Da||zj(a);a.Tm?a.Tm.next=b:a.vj=b;a.Tm=b};
uj=function(a,b,c,d){var e=_.nj(null,null,null);e.Uk=new _.kj(function(a,h){e.gr=b?function(c){try{var e=b.call(d,c);a(e)}catch(n){h(n)}}:a;e.On=c?function(b){try{var e=c.call(d,b);!_.r(e)&&b instanceof vj?h(b):a(e)}catch(n){h(n)}}:h});e.Uk.hb=a;_.Aj(a,e);return e.Uk};_.kj.prototype.f0=function(a){this.Da=0;this.Wg(2,a)};_.kj.prototype.g0=function(a){this.Da=0;this.Wg(3,a)};
_.kj.prototype.Wg=function(a,b){0==this.Da&&(this===b&&(a=3,b=new TypeError("Promise cannot resolve to itself")),this.Da=1,qj(b,this.f0,this.g0,this)||(this.Pi=b,this.Da=a,this.hb=null,zj(this),3!=a||b instanceof vj||Bj(this,b)))};
var qj=function(a,b,c,d){if(a instanceof _.kj)return _.Aj(a,_.nj(b||_.Ta,c||null,d)),!0;if(_.jj(a))return a.then(b,c,d),!0;if(_.Wa(a))try{var e=a.then;if(_.Va(e))return Cj(a,e,b,c,d),!0}catch(f){return c.call(d,f),!0}return!1},Cj=function(a,b,c,d,e){var f=!1,h=function(a){f||(f=!0,c.call(e,a))},k=function(a){f||(f=!0,d.call(e,a))};try{b.call(a,h,k)}catch(l){k(l)}},zj=function(a){a.fz||(a.fz=!0,_.gj(a.SR,a))},xj=function(a){var b=null;a.vj&&(b=a.vj,a.vj=b.next,b.next=null);a.vj||(a.Tm=null);return b};
_.kj.prototype.SR=function(){for(var a;a=xj(this);)yj(this,a,this.Da,this.Pi);this.fz=!1};var yj=function(a,b,c,d){if(3==c&&b.On&&!b.Yo)for(;a&&a.uu;a=a.hb)a.uu=!1;if(b.Uk)b.Uk.hb=null,Dj(b,c,d);else try{b.Yo?b.gr.call(b.context):Dj(b,c,d)}catch(e){Ej.call(null,e)}mj.put(b)},Dj=function(a,b,c){2==b?a.gr.call(a.context,c):a.On&&a.On.call(a.context,c)},Bj=function(a,b){a.uu=!0;_.gj(function(){a.uu&&Ej.call(null,b)})},Ej=Vi,vj=function(a){_.Pi.call(this,a)};_.B(vj,_.Pi);vj.prototype.name="cancel"; var sj=function(a,b,c){this.promise=a;this.resolve=b;this.reject=c};

_.Fj=function(a){return new _.kj(a)};
_.Gj=_.Gj||{};_.Gj.$T=function(){var a=0,b=0;window.self.innerHeight?(a=window.self.innerWidth,b=window.self.innerHeight):window.document.documentElement&&window.document.documentElement.clientHeight?(a=window.document.documentElement.clientWidth,b=window.document.documentElement.clientHeight):window.document.body&&(a=window.document.body.clientWidth,b=window.document.body.clientHeight);return{width:a,height:b}};

_.Gj=_.Gj||{};
(function(){function a(a,c){window.getComputedStyle(a,"").getPropertyValue(c).match(/^([0-9]+)/);return(0,window.parseInt)(RegExp.$1,10)}_.Gj.Wc=function(){var b=_.Gj.$T().height,c=window.document.body,d=window.document.documentElement;if("CSS1Compat"===window.document.compatMode&&d.scrollHeight)return d.scrollHeight!==b?d.scrollHeight:d.offsetHeight;if(0<=window.navigator.userAgent.indexOf("AppleWebKit")){b=0;for(c=[window.document.body];0<c.length;){var e=c.shift();d=e.childNodes;if("undefined"!==
typeof e.style){var f=e.style.overflowY;f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.overflowY:null);if("visible"!=f&&"inherit"!=f&&(f=e.style.height,f||(f=(f=window.document.defaultView.getComputedStyle(e,null))?f.height:""),0<f.length&&"auto"!=f))continue}for(e=0;e<d.length;e++){f=d[e];if("undefined"!==typeof f.offsetTop&&"undefined"!==typeof f.offsetHeight){var h=f.offsetTop+f.offsetHeight+a(f,"margin-bottom");b=Math.max(b,h)}c.push(f)}}return b+a(window.document.body,"border-bottom")+ a(window.document.body,"margin-bottom")+a(window.document.body,"padding-bottom")}if(c&&d)return e=d.scrollHeight,f=d.offsetHeight,d.clientHeight!==f&&(e=c.scrollHeight,f=c.offsetHeight),e>b?e>f?e:f:e<f?e:f}})();

_.Ik=function(a){this.R=a};_.g=_.Ik.prototype;_.g.value=function(){return this.R};_.g.zk=function(a){this.R.width=a;return this};_.g.Ed=function(){return this.R.width};_.g.wk=function(a){this.R.height=a;return this};_.g.Wc=function(){return this.R.height};_.g.wd=function(a){this.R.style=a;return this};_.g.Cl=_.da(5);
var Jk=function(a){this.R=a};Jk.prototype.no=function(a){this.R.anchor=a;return this};Jk.prototype.vf=function(){return this.R.anchor};Jk.prototype.OC=function(a){this.R.anchorPosition=a;return this};_.Kk=function(a){a.R.show=!0;return a};Jk.prototype.wk=function(a){this.R.height=a;return this};Jk.prototype.Wc=function(){return this.R.height};Jk.prototype.zk=function(a){this.R.width=a;return this};Jk.prototype.Ed=function(){return this.R.width};
_.Lk=function(a){this.R=a||{}};_.g=_.Lk.prototype;_.g.value=function(){return this.R};_.g.setUrl=function(a){this.R.url=a;return this};_.g.getUrl=function(){return this.R.url};_.g.wd=function(a){this.R.style=a;return this};_.g.Cl=_.da(4);_.g.Yg=function(a){this.R.id=a};_.g.ka=function(){return this.R.id};_.g.yk=_.da(6);_.Mk=function(a,b){a.R.queryParams=b;return a};_.Nk=function(a,b){a.R.relayOpen=b;return a};_.Ok=function(a,b){a.R.messageHandlersFilter=b;return a};_.Lk.prototype.oo=_.da(7);
_.Pk=function(a,b){a.R.openAsWindow=b;return a};_.Lk.prototype.getContext=function(){return this.R.context};_.Lk.prototype.Pc=function(){return this.R.openerIframe};_.Qk=function(a){return new Jk(a.R)};_.Lk.prototype.cn=function(){this.R.attributes=this.R.attributes||{};return new _.Ik(this.R.attributes)};_.Rk=function(a){a.R.connectWithQueryParams=!0;return a};

var Sk,Xk,Yk,Zk,el,dl;_.Ik.prototype.Cl=_.qc(5,function(){return this.R.style});_.Lk.prototype.Cl=_.qc(4,function(){return this.R.style});Sk=function(a,b){a.R.onload=b};_.Tk=function(a){a.R.closeClickDetection=!0};_.Uk=function(a){return a.R.rpctoken};_.Vk=function(a,b){a.R.messageHandlers=b;return a};_.Wk=function(a){a.R.waitForOnload=!0;return a};Xk=function(a){return(a=a.R.timeout)?a:null};
_.al=function(a,b,c){if(a){_.Vj(_.Tj(a),"arrayForEach was called with a non array value");for(var d=0;d<a.length;d++)b.call(c,a[d],d)}};_.bl=function(a,b,c){if(a)if(_.Tj(a))_.al(a,b,c);else{_.Vj("object"===typeof a,"objectForEach was called with a non object value");c=c||a;for(var d in a)_.Ud(a,d)&&void 0!==a[d]&&b.call(c,a[d],d)}};
_.cl=function(a){return new _.kj(function(b,c){var d=a.length,e=[];if(d)for(var f=function(a,c){d--;e[a]=c;0==d&&b(e)},h=function(a){c(a)},k=0,l;k<a.length;k++)l=a[k],_.rj(l,_.Gi(f,k),h);else b(e)})};el=function(a){this.resolve=this.reject=null;this.promise=_.Fj((0,_.C)(function(a,c){this.resolve=a;this.reject=c},this));a&&(this.promise=dl(this.promise,a))};dl=function(a,b){return a.then(function(a){try{b(a)}catch(d){}return a})};
_.fl=function(a){this.R=a||{}};_.B(_.fl,_.Lk);_.gl=function(a,b){a.R.frameName=b;return a};_.fl.prototype.Bd=function(){return this.R.frameName};_.hl=function(a,b){a.R.rpcAddr=b;return a};_.fl.prototype.Al=function(){return this.R.rpcAddr};_.il=function(a,b){a.R.retAddr=b;return a};_.jl=function(a){return a.R.retAddr};_.fl.prototype.Nh=function(a){this.R.origin=a;return this};_.fl.prototype.Qa=function(){return this.R.origin};_.fl.prototype.Vi=function(a){this.R.setRpcReady=a;return this};_.kl=function(a){return a.R.setRpcReady}; _.fl.prototype.ro=function(a){this.R.context=a};var ll=function(a,b){a.R._rpcReadyFn=b};_.fl.prototype.Ha=function(){return this.R.iframeEl};
var ml,ql,pl;ml=/^[\w\.\-]*$/;_.nl=function(a){return a.vd===a.getContext().vd};_.P=function(){return!0};_.ol=function(a){for(var b=_.G(),c=0;c<a.length;c++)b[a[c]]=!0;return function(a){return!!b[a.vd]}};ql=function(a,b,c){return function(d){if(!b.Eb){_.Vj(this.origin===b.vd,"Wrong origin "+this.origin+" != "+b.vd);var e=this.callback;d=pl(a,d,b);!c&&0<d.length&&_.cl(d).then(e)}}};pl=function(a,b,c){a=Yk[a];if(!a)return[];for(var d=[],e=0;e<a.length;e++)d.push(_.oj(a[e].call(c,b,c)));return d};
_.rl=function(a,b,c){_.Vj("_default"!=a,"Cannot update default api");Zk[a]={map:b,filter:c}};_.sl=function(a,b,c){_.Vj("_default"!=a,"Cannot update default api");_.Td(Zk,a,{map:{},filter:_.nl}).map[b]=c};_.tl=function(a,b){_.Td(Zk,"_default",{map:{},filter:_.P}).map[a]=b;_.bl(_.$k.Je,function(c){c.register(a,b,_.P)})};_.ul=function(){return _.$k};
_.wl=function(a){a=a||{};this.Eb=!1;this.wK=_.G();this.Je=_.G();this.Ge=a._window||_.Nd;this.xd=this.Ge.location.href;this.xK=(this.SB=vl(this.xd,"parent"))?vl(this.xd,"pfname"):"";this.Aa=this.SB?vl(this.xd,"_gfid")||vl(this.xd,"id"):"";this.uf=_.xk(this.Aa,this.xK);this.vd=_.Rf.Qa(this.xd);if(this.Aa){var b=new _.fl;_.hl(b,a._parentRpcAddr||"..");_.il(b,a._parentRetAddr||this.Aa);b.Nh(_.Rf.Qa(this.SB||this.xd));_.gl(b,this.xK);this.hb=this.rj(b.value())}else this.hb=null};_.g=_.wl.prototype;
_.g.Dn=_.da(9);_.g.Ca=function(){if(!this.Eb){for(var a=0;a<this.Je.length;a++)this.Je[a].Ca();this.Eb=!0}};_.g.Bd=function(){return this.uf};_.g.ub=function(){return this.Ge};_.g.mb=function(){return this.Ge.document};_.g.ow=_.da(10);_.g.Hz=function(a){return this.wK[a]};
_.g.rj=function(a){_.Vj(!this.Eb,"Cannot attach iframe in disposed context");a=new _.fl(a);a.Al()||_.hl(a,a.ka());_.jl(a)||_.il(a,"..");a.Qa()||a.Nh(_.Rf.Qa(a.getUrl()));a.Bd()||_.gl(a,_.xk(a.ka(),this.uf));var b=a.Bd();if(this.Je[b])return this.Je[b];var c=a.Al(),d=c;a.Qa()&&(d=c+"|"+a.Qa());var e=_.jl(a),f=_.Uk(a);f||(f=(f=a.Ha())&&(f.getAttribute("data-postorigin")||f.src)||a.getUrl(),f=_.Xd(f,"rpctoken"));ll(a,_.Fi(d,e,f,a.R._popupWindow));d=((window.gadgets||{}).rpc||{}).setAuthToken;f&&d&&d(c,
f);var h=new _.xl(this,c,b,a),k=a.R.messageHandlersFilter;_.bl(a.R.messageHandlers,function(a,b){h.register(b,a,k)});_.kl(a)&&h.Vi();_.yl(h,"_g_rpcReady");return h};_.g.yC=function(a){_.gl(a,null);var b=a.ka();!b||ml.test(b)&&!this.ub().document.getElementById(b)||(_.ve("Ignoring requested iframe ID - "+b),a.Yg(null))};var vl=function(a,b){var c=_.Xd(a,b);c||(c=_.ef(_.Xd(a,"jcp",""))[b]);return c||""};
_.wl.prototype.Sg=function(a){_.Vj(!this.Eb,"Cannot open iframe in disposed context");var b=new _.fl(a);zl(this,b);var c=b.Bd();if(c&&this.Je[c])return this.Je[c];this.yC(b);c=b.getUrl();_.Vj(c,"No url for new iframe");var d=b.R.queryParams||{};d.usegapi="1";_.Mk(b,d);d=this.sI&&this.sI(c,b);d||(d=b.R.where,_.Vj(!!d,"No location for new iframe"),c=_.Hk(c,d,a),b.R.iframeEl=c,d=c.getAttribute("id"));_.hl(b,d).Yg(d);b.Nh(_.Rf.Qa(b.R.eurl||""));this.CJ&&this.CJ(b,b.Ha());c=this.rj(a);c.hD&&c.hD(c,a);
(a=b.R.onCreate)&&a(c);b.R.disableRelayOpen||c.$o("_open");return c};
var Al=function(a,b,c){var d=b.R.canvasUrl;if(!d)return c;_.Vj(!b.R.allowPost&&!b.R.forcePost,"Post is not supported when using canvas url");var e=b.getUrl();_.Vj(e&&_.Rf.Qa(e)===a.vd&&_.Rf.Qa(d)===a.vd,"Wrong origin for canvas or hidden url "+d);b.setUrl(d);_.Wk(b);b.R.canvasUrl=null;return function(a){var b=a.ub(),d=b.location.hash;d=_.Gk(e)+(/#/.test(e)?d.replace(/^#/,"&"):d);b.location.replace(d);c&&c(a)}},Cl=function(a,b,c){var d=b.R.relayOpen;if(d){var e=a.hb;d instanceof _.xl?(e=d,_.Nk(b,0)):
0<Number(d)&&_.Nk(b,Number(d)-1);if(e){_.Vj(!!e.oK,"Relaying iframe open is disabled");if(d=b.Cl())if(d=_.Bl[d])b.ro(a),d(b.value()),b.ro(null);b.R.openerIframe=null;c.resolve(e.oK(b));return!0}}return!1},Gl=function(a,b,c){var d=b.Cl();if(d)if(_.Vj(!!_.Dl,"Defer style is disabled, when requesting style "+d),_.El[d])zl(a,b);else return Fl(d,function(){_.Vj(!!_.El[d],"Fail to load style - "+d);c.resolve(a.open(b.value()))}),!0;return!1};
_.wl.prototype.open=function(a,b){_.Vj(!this.Eb,"Cannot open iframe in disposed context");var c=new _.fl(a);b=Al(this,c,b);var d=new el(b);(b=c.getUrl())&&c.setUrl(_.Gk(b));if(Cl(this,c,d)||Gl(this,c,d)||Cl(this,c,d))return d.promise;if(null!=Xk(c)){var e=(0,window.setTimeout)(function(){h.Ha().src="about:blank";d.reject({timeout:"Exceeded time limit of :"+Xk(c)+"milliseconds"})},Xk(c)),f=d.resolve;d.resolve=function(a){(0,window.clearTimeout)(e);f(a)}}c.R.waitForOnload&&Sk(c.cn(),function(){d.resolve(h)});
var h=this.Sg(a);c.R.waitForOnload||d.resolve(h);return d.promise};_.wl.prototype.LH=_.da(11);_.xl=function(a,b,c,d){this.Eb=!1;this.Nd=a;this.Qi=b;this.uf=c;this.ya=d;this.eo=_.jl(this.ya);this.vd=this.ya.Qa();this.SV=this.ya.Ha();this.kM=this.ya.R.where;this.Un=[];this.$o("_default");a=this.ya.R.apis||[];for(b=0;b<a.length;b++)this.$o(a[b]);this.Nd.Je[c]=this};_.g=_.xl.prototype;_.g.Dn=_.da(8);
_.g.Ca=function(){if(!this.Eb){for(var a=0;a<this.Un.length;a++)this.unregister(this.Un[a]);delete _.$k.Je[this.Bd()];this.Eb=!0}};_.g.getContext=function(){return this.Nd};_.g.Al=function(){return this.Qi};_.g.Bd=function(){return this.uf};_.g.Ha=function(){return this.SV};_.g.$a=function(){return this.kM};_.g.df=function(a){this.kM=a};_.g.Vi=function(){(0,this.ya.R._rpcReadyFn)()};_.g.LL=function(a,b){this.ya.value()[a]=b};_.g.Qz=function(a){return this.ya.value()[a]};_.g.Ob=function(){return this.ya.value()};
_.g.ka=function(){return this.ya.ka()};_.g.Qa=function(){return this.vd};_.g.register=function(a,b,c){_.Vj(!this.Eb,"Cannot register handler on disposed iframe "+a);_.Vj((c||_.nl)(this),"Rejecting untrusted message "+a);c=this.uf+":"+this.Nd.uf+":"+a;1==_.Td(Yk,c,[]).push(b)&&(this.Un.push(a),_.ui(c,ql(c,this,"_g_wasClosed"===a)))};
_.g.unregister=function(a,b){var c=this.uf+":"+this.Nd.uf+":"+a,d=Yk[c];d&&(b?(b=_.Uj.call(d,b),0<=b&&d.splice(b,1)):d.splice(0,d.length),0==d.length&&(b=_.Uj.call(this.Un,a),0<=b&&this.Un.splice(b,1),_.vi(c)))};_.g.IT=function(){return this.Un};_.g.$o=function(a){this.Kx=this.Kx||[];if(!(0<=_.Uj.call(this.Kx,a))){this.Kx.push(a);a=Zk[a]||{map:{}};for(var b in a.map)_.Ud(a.map,b)&&this.register(b,a.map[b],a.filter)}};
_.g.send=function(a,b,c,d){_.Vj(!this.Eb,"Cannot send message to disposed iframe - "+a);_.Vj((d||_.nl)(this),"Wrong target for message "+a);c=new el(c);_.yi(this.Qi,this.Nd.uf+":"+this.uf+":"+a,c.resolve,b);return c.promise};_.yl=function(a,b,c,d){return a.send(b,c,d,_.P)};_.xl.prototype.$X=function(a){return a};_.xl.prototype.ping=function(a,b){return _.yl(this,"_g_ping",b,a)};Yk=_.G();Zk=_.G();_.$k=new _.wl;_.tl("_g_rpcReady",_.xl.prototype.Vi);_.tl("_g_discover",_.xl.prototype.IT); _.tl("_g_ping",_.xl.prototype.$X);
var Fl,zl;_.El=_.G();_.Bl=_.G();_.Dl=function(a){return _.El[a]};Fl=function(a,b){_.Wd.load("gapi.iframes.style."+a,b)};zl=function(a,b){var c=b.Cl();if(c){b.wd(null);var d=_.El[c];_.Vj(d,"No such style: "+c);b.ro(a);d(b.value());b.ro(null)}};var Hl,Il;Hl={height:!0,width:!0};Il=/^(?!-*(?:expression|(?:moz-)?binding))(?:[.#]?-?(?:[_a-z0-9-]+)(?:-[_a-z0-9-]+)*-?|-?(?:[0-9]+(?:\.[0-9]*)?|\.[0-9]+)(?:[a-z]{1,2}|%)?|!important|)$/i;_.Jl=function(a){"number"===typeof a&&(a=String(a)+"px");return a};_.xl.prototype.ub=function(){if(!_.nl(this))return null;var a=this.ya.R._popupWindow;if(a)return a;var b=this.Qi.split("/");a=this.getContext().ub();for(var c=0;c<b.length&&a;c++){var d=b[c];a=".."===d?a==a.parent?a.opener:a.parent:a.frames[d]}return a};
var Kl=function(a,b){var c=a.hb,d=!0;b.filter&&(d=b.filter.call(b.xf,b.params));return _.oj(d).then(function(d){return d&&c?(b.vK&&b.vK.call(a,b.params),d=b.sender?b.sender(b.params):_.yl(c,b.message,b.params),b.y0?d.then(function(){return!0}):!0):!1})};
_.wl.prototype.jy=function(a,b,c){a=Kl(this,{sender:function(a){var b=_.$k.hb;_.bl(_.$k.Je,function(c){c!==b&&_.yl(c,"_g_wasClosed",a)});return _.yl(b,"_g_closeMe",a)},message:"_g_closeMe",params:a,xf:c,filter:this.Hz("onCloseSelfFilter")});b=new el(b);b.resolve(a);return b.promise};_.wl.prototype.vC=function(a,b,c){a=a||{};b=new el(b);b.resolve(Kl(this,{message:"_g_restyleMe",params:a,xf:c,filter:this.Hz("onRestyleSelfFilter"),y0:!0,vK:this.MM}));return b.promise};
_.wl.prototype.MM=function(a){"auto"===a.height&&(a.height=_.Gj.Wc())};_.Ll=function(a){var b={};if(a)for(var c in a)_.Ud(a,c)&&_.Ud(Hl,c)&&Il.test(a[c])&&(b[c]=a[c]);return b};_.g=_.xl.prototype;_.g.close=function(a,b){return _.yl(this,"_g_close",a,b)};_.g.Br=function(a,b){return _.yl(this,"_g_restyle",a,b)};_.g.bo=function(a,b){return _.yl(this,"_g_restyleDone",a,b)};_.g.dR=function(a){return this.getContext().jy(a,void 0,this)};
_.g.YY=function(a){if(a&&"object"===typeof a)return this.getContext().vC(a,void 0,this)};_.g.ZY=function(a){var b=this.ya.R.onRestyle;b&&b.call(this,a,this);a=a&&"object"===typeof a?_.Ll(a):{};(b=this.Ha())&&a&&"object"===typeof a&&(_.Ud(a,"height")&&(a.height=_.Jl(a.height)),_.Ud(a,"width")&&(a.width=_.Jl(a.width)),_.Vd(a,b.style))};
_.g.eR=function(a){var b=this.ya.R.onClose;b&&b.call(this,a,this);this.pG&&this.pG()||(b=this.Ha())&&b.parentNode&&b.parentNode.removeChild(b);if(b=this.ya.R.controller){var c={};c.frameName=this.Bd();_.yl(b,"_g_disposeControl",c)}pl(this.uf+":"+this.Nd.uf+":_g_wasClosed",a,this)};_.wl.prototype.wL=_.da(12);_.wl.prototype.OL=_.da(13);_.xl.prototype.NK=_.da(14);_.xl.prototype.mk=function(a,b){this.register("_g_wasClosed",a,b)};
_.xl.prototype.B0=function(){delete this.getContext().Je[this.Bd()];this.getContext().ub().setTimeout((0,_.C)(function(){this.Ca()},this),0)};_.tl("_g_close",_.xl.prototype.dR);_.tl("_g_closeMe",_.xl.prototype.eR);_.tl("_g_restyle",_.xl.prototype.YY);_.tl("_g_restyleMe",_.xl.prototype.ZY);_.tl("_g_wasClosed",_.xl.prototype.B0);

_.xl.prototype.NK=_.qc(14,function(a,b){this.register("_g_wasRestyled",a,b)});_.g=_.wl.prototype;_.g.OL=_.qc(13,function(a){this.ow("onRestyleSelfFilter",a)});_.g.wL=_.qc(12,function(a){this.ow("onCloseSelfFilter",a)});_.g.LH=_.qc(11,function(){return this.hb});_.g.ow=_.qc(10,function(a,b){this.wK[a]=b});_.g.Dn=_.qc(9,function(){return this.Eb});_.xl.prototype.Dn=_.qc(8,function(){return this.Eb});_.w("gapi.iframes.registerStyle",function(a,b){_.El[a]=b});
_.w("gapi.iframes.registerBeforeOpenStyle",function(a,b){_.Bl[a]=b});_.w("gapi.iframes.getStyle",_.Dl);_.w("gapi.iframes.getBeforeOpenStyle",function(a){return _.Bl[a]});_.w("gapi.iframes.registerIframesApi",_.rl);_.w("gapi.iframes.registerIframesApiHandler",_.sl);_.w("gapi.iframes.getContext",_.ul);_.w("gapi.iframes.SAME_ORIGIN_IFRAMES_FILTER",_.nl);_.w("gapi.iframes.CROSS_ORIGIN_IFRAMES_FILTER",_.P);_.w("gapi.iframes.makeWhiteListIframesFilter",_.ol);_.w("gapi.iframes.Context",_.wl);
_.w("gapi.iframes.Context.prototype.isDisposed",_.wl.prototype.Dn);_.w("gapi.iframes.Context.prototype.getWindow",_.wl.prototype.ub);_.w("gapi.iframes.Context.prototype.getFrameName",_.wl.prototype.Bd);_.w("gapi.iframes.Context.prototype.getGlobalParam",_.wl.prototype.Hz);_.w("gapi.iframes.Context.prototype.setGlobalParam",_.wl.prototype.ow);_.w("gapi.iframes.Context.prototype.open",_.wl.prototype.open);_.w("gapi.iframes.Context.prototype.openChild",_.wl.prototype.Sg);
_.w("gapi.iframes.Context.prototype.getParentIframe",_.wl.prototype.LH);_.w("gapi.iframes.Context.prototype.closeSelf",_.wl.prototype.jy);_.w("gapi.iframes.Context.prototype.restyleSelf",_.wl.prototype.vC);_.w("gapi.iframes.Context.prototype.setCloseSelfFilter",_.wl.prototype.wL);_.w("gapi.iframes.Context.prototype.setRestyleSelfFilter",_.wl.prototype.OL);_.w("gapi.iframes.Iframe",_.xl);_.w("gapi.iframes.Iframe.prototype.isDisposed",_.xl.prototype.Dn);
_.w("gapi.iframes.Iframe.prototype.getContext",_.xl.prototype.getContext);_.w("gapi.iframes.Iframe.prototype.getFrameName",_.xl.prototype.Bd);_.w("gapi.iframes.Iframe.prototype.getId",_.xl.prototype.ka);_.w("gapi.iframes.Iframe.prototype.register",_.xl.prototype.register);_.w("gapi.iframes.Iframe.prototype.unregister",_.xl.prototype.unregister);_.w("gapi.iframes.Iframe.prototype.send",_.xl.prototype.send);_.w("gapi.iframes.Iframe.prototype.applyIframesApi",_.xl.prototype.$o);
_.w("gapi.iframes.Iframe.prototype.getIframeEl",_.xl.prototype.Ha);_.w("gapi.iframes.Iframe.prototype.getSiteEl",_.xl.prototype.$a);_.w("gapi.iframes.Iframe.prototype.setSiteEl",_.xl.prototype.df);_.w("gapi.iframes.Iframe.prototype.getWindow",_.xl.prototype.ub);_.w("gapi.iframes.Iframe.prototype.getOrigin",_.xl.prototype.Qa);_.w("gapi.iframes.Iframe.prototype.close",_.xl.prototype.close);_.w("gapi.iframes.Iframe.prototype.restyle",_.xl.prototype.Br);
_.w("gapi.iframes.Iframe.prototype.restyleDone",_.xl.prototype.bo);_.w("gapi.iframes.Iframe.prototype.registerWasRestyled",_.xl.prototype.NK);_.w("gapi.iframes.Iframe.prototype.registerWasClosed",_.xl.prototype.mk);_.w("gapi.iframes.Iframe.prototype.getParam",_.xl.prototype.Qz);_.w("gapi.iframes.Iframe.prototype.setParam",_.xl.prototype.LL);_.w("gapi.iframes.Iframe.prototype.ping",_.xl.prototype.ping);

});
// Google Inc.
